
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.4 EDK_2013.4.20131205
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_LCD_11BIT_DEVICE_ID,
		XPAR_LCD_11BIT_BASEADDR,
		XPAR_LCD_11BIT_INTERRUPT_PRESENT,
		XPAR_LCD_11BIT_IS_DUAL
	},
	{
		XPAR_LED_2BIT_DEVICE_ID,
		XPAR_LED_2BIT_BASEADDR,
		XPAR_LED_2BIT_INTERRUPT_PRESENT,
		XPAR_LED_2BIT_IS_DUAL
	}
};


